/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],

  // But you can create a sidebar manually
  
  docSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Les fonctionalités de Eliobot',
      link: {type: 'doc', id: 'eliobot'},
      items: [
        "eliobot/led",
        "eliobot/button",
        "eliobot/buzzer",
        "eliobot/motors",
        "eliobot/sensors-proximity",
        "eliobot/sensors-line",
        "eliobot/battery",
        "eliobot/wifi",
        "eliobot/backpacks",
      ],
    },
    {
      type: 'category',
      label: "L'application Elioblocs",
      link: {type: 'doc', id: 'elioblocs'},
      items: [
        "elioblocs/interface",
        "elioblocs/terminal",
        {
          type: 'category',
          label: "Tous les blocs",
          items: [
            "elioblocs/blocs/conditions",
            "elioblocs/blocs/loops",
            "elioblocs/blocs/maths",
            "elioblocs/blocs/lists",
            "elioblocs/blocs/text",
            "elioblocs/blocs/variables",
            "elioblocs/blocs/functions",
            "elioblocs/blocs/colors",
            "elioblocs/blocs/sounds",
            "elioblocs/blocs/movements",
            "elioblocs/blocs/obstacles",
            "elioblocs/blocs/line",
            "elioblocs/blocs/utilities",
            "elioblocs/blocs/backpacks",
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'Librairie Python',
      items: [
        "python_lib/intro",
      ],
    },
    {
      type: 'category',
      label: 'Librairie Arduino',
      items: [
        "arduino_lib/intro",
      ],
    },
    {
      type: 'category',
      label: 'Liens Utiles',
      items: [
        {
          type: 'link',
          label: 'Fichiers 3D',
          href: 'https://www.printables.com/@eliobot_387275'
        },
        {
          type: 'link',
          label: 'Github',
          href: 'https://github.com/Eliobot'
        },
      ],
    },
  ]


   
};

export default sidebars;
